[ADD] Styling ampalibe cli bash

diff --git a/bin/ampalibe b/bin/ampalibe
--- a/bin/ampalibe
+++ b/bin/ampalibe
@@ -3,42 +3,57 @@
 if [ "$1" == "create" ]; then
     if [ $# -eq 2 ]; then
         if [ -d "$2" ]; then
-            echo "Dossier $2 existant"
+            >&2 echo -e "~\033[31m ERROR :(\033[0m ~ A folder $2 already exists"
             exit 1
         fi
-        mkdir $2
-        python -c "import ampalibe;print(ampalibe.env)" > $2/.env
-        python -c "import ampalibe;print(ampalibe.conf)" > $2/conf.py
-        python -c "import ampalibe;print(ampalibe.core)" > $2/core.py
+        mkdir $2; 
+            echo -e "~\033[32m :)\033[0m | Creating $2 ...";
+        python -c "import ampalibe;print(ampalibe.env)" > $2/.env;
+            echo -e "~\033[32m :)\033[0m | Env file created";
+        python -c "import ampalibe;print(ampalibe.conf)" > $2/conf.py;
+            echo -e "~\033[32m :)\033[0m | Config file created";
+        python -c "import ampalibe;print(ampalibe.core)" > $2/core.py;
+            echo -e "~\033[32m :)\033[0m | Core file created";
         mkdir -p $2/assets/{public,private}
+            echo -e "~\033[32m :)\033[0m | Project Ampalibe created. \033[32mYoupii !!! *_* \033[0m";
+            echo -e "~\033[36m TIPS\033[0m |\033[0m Fill in .env file."
+            echo -e "~\033[36m TIPS\033[0m |\033[36m ampalibe run\033[0m for lauching project."
+        cd $2;
     else
-        echo "Incorrect number of args for create"
+        echo -e "~\033[31m ERROR :(\033[0m | Incorrect number of args for create"
         exit 1
     fi
 elif [ "$1" == "init" ]; then
     if [ $# -eq 1 ]; then
-        python -c "import ampalibe;print(ampalibe.env)" > .env
-        python -c "import ampalibe;print(ampalibe.conf)" > conf.py
-        python -c "import ampalibe;print(ampalibe.core)" > core.py
+        python -c "import ampalibe;print(ampalibe.env)" > .env;
+            echo -e "~\033[32m :)\033[0m | Env file created";
+        python -c "import ampalibe;print(ampalibe.conf)" > conf.py;
+            echo -e "~\033[32m :)\033[0m | Config file created";
+        python -c "import ampalibe;print(ampalibe.core)" > core.py;
+            echo -e "~\033[32m :)\033[0m | Core file created";
         mkdir -p assets/{public,private}
+            echo -e "~\033[32m :)\033[0m | Project Ampalibe initiated. \033[32mYoupii !!! *_* \033[0m";
+            echo -e "~\033[36m TIPS\033[0m |\033[36m ampalibe run\033[0m for lauching project."
     else
-        echo "Incorrect number of args for init"
+        >&2 echo -e "~\033[31m ERROR :(\033[0m | Incorrect number of args for init"
         exit 1
         
     fi
 elif [ "$1" == "run" ]; then
     if [ $# -eq 1 ]; then
         if ! [ -f "core.py" ]; then
-            echo "core.py not found\nPlease, go to your dir project."
+            >&2 echo -e "~ \033[31mERROR :(\033[0m | core.py not found\n~\033[36m TIPS :)\033[0m ~\033[0m Please, go to your dir project.";
             exit 1
         fi
-        source .env
+        source .env;
+            echo -e "~\033[32m :)\033[0m | Env Loaded";
+            echo -e "~\033[32m :)\033[0m | Ampalibe running...";
         python -c 'import core;core.ampalibe.run(core.Configuration())'
     else
-        echo "Incorrect number of args for run"
+        >&2 echo -e "~\033[31m ERROR :(\033[0m | Incorrect number of args for run"
         exit 1
     fi
 else
-    echo "Missing knowing argument"
+    >&2 echo -e "~\033[31m ERROR :(\033[0m | Missing knowing argument"
     exit 1
 fi
