[ADD] Linux Script

diff --git a/bin/ampalibe b/bin/ampalibe
--- a/bin/ampalibe
+++ b/bin/ampalibe
@@ -1,2 +1,45 @@
 #!/bin/bash
 
+if [ "$1" == "create" ]; then
+    if [ $# -eq 2 ]; then
+        if [ -d "$2" ]; then
+            echo "Dossier $2 existant"
+            exit 1
+        fi
+        mkdir $2
+        python -c "import ampalibe;print(ampalibe.env)" > $2/.env
+        python -c "import ampalibe;print(ampalibe.conf)" > $2/conf.py
+        python -c "import ampalibe;print(ampalibe.core)" > $2/core.py
+        python -c "import ampalibe;print(ampalibe.server)" > $2/server.py
+        mkdir -p $2/assets/{public,private}
+    else
+        echo "Incorrect number of args for create"
+        exit 1
+    fi
+elif [ "$1" == "init" ]; then
+    if [ $# -eq 1 ]; then
+        python -c "import ampalibe;print(ampalibe.env)" > .env
+        python -c "import ampalibe;print(ampalibe.conf)" > conf.py
+        python -c "import ampalibe;print(ampalibe.core)" > core.py
+        python -c "import ampalibe;print(ampalibe.server)" > server.py
+        mkdir -p assets/{public,private}
+    else
+        echo "Incorrect number of args for init"
+        exit 1
+        
+    fi
+elif [ "$1" == "run" ]; then
+    if [ $# -eq 1 ]; then
+        if ! [ -f "server.py" ]; then
+            echo "server.py not found\nPlease, go to your dir project."
+            exit 1
+        fi
+        python server.py
+    else
+        echo "Incorrect number of args for run"
+        exit 1
+    fi
+else
+    echo "Missing knowing argument"
+    exit 1
+fi
