[ADD] Add text guide on Batch File

diff --git a/bin/ampalibe b/bin/ampalibe
--- a/bin/ampalibe
+++ b/bin/ampalibe
@@ -17,7 +17,7 @@ fi
 if [ "$1" == "create" ]; then
     if [ $# -eq 2 ]; then
         if [ -d "$2" ]; then
-            >&2 echo -e "~\033[31m ERROR !!\033[0m ~ A folder $2 already exists"
+            >&2 echo -e "~\033[31m ERROR 😱\033[0m ~ A folder $2 already exists"
             exit 1
         fi
         mkdir $2; 
@@ -72,13 +72,11 @@ elif [ "$1" == "run" ]; then
  /_/   \_\_|  |_|_| /_/   \_\_____|___|____/|_____|         oooooo \033[0m
  
  """
-            echo -e "~\033[32m 👌\033[0m | Env Loaded";
-            echo -e "~\033[32m 👌\033[0m | Ampalibe running...";
-        if [ $python = "python3" ]; then
-            python3 -c 'import core;core.ampalibe.init.run(core.Configuration())'
-        else
-            python -c 'import core;core.ampalibe.init.run(core.Configuration())'
-        fi
+        echo -e "~\033[32m 👌\033[0m | Env Loaded";
+        echo -e "~\033[32m 👌\033[0m | Ampalibe running...";
+
+        $python -c 'import core;core.ampalibe.init.run(core.Configuration())'
+
     else
         >&2 echo -e "~\033[31m ERROR 👌\033[0m | Incorrect number of args for run"
         exit 1
